# Generated by Django 5.2.4 on 2025-07-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=15, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
